run:
  deadline: 5m
  issues-exit-code: 1
linters:
  enable-all: true
  disable:
    - errcheck
    - gochecknoglobals
    - lll
    - unparam
    - goconst
linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: "github.com/ispringteam/go-patterns"
  gocritic:
    enabled-tags:
      - opinionated
